# -*- coding: utf-8 -*-
"""GEN_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLERRKWNKbCMxfhe25VWoh_kbA3Xmg-6
"""

!pip install gradio transformers easyocr gTTS deep-translator google-generativeai

!pip install easyocr
!pip install gtts
!pip install google-genai

import gradio as gr
from transformers import pipeline
import easyocr
from gtts import gTTS
from google import genai
from deep_translator import GoogleTranslator # Import GoogleTranslator
import tempfile # Import tempfile for temporary audio files

client = genai.Client(api_key="AIzaSyAaJYMRnUBpTBIVoq_DcelYgj4Yq3XaClA")


# # --- Configure Gemini API ---
# gemini_model = genai.GenerativeModel("gemini-3-flash-preview")

# --- Load models ---
summarizer = pipeline(
    "text-generation", # Changed from 'summarization' to 'text-generation' as 'summarization' was not recognized
    model="facebook/bart-large-cnn"
)

qa_pipeline = pipeline("question-answering")
ocr_reader = easyocr.Reader(['en'])

# --- Define Functions ---

def ocr_from_image(img_path):
    print("OCR function triggered.")
    result = ocr_reader.readtext(img_path, detail=0)
    return " ".join(result)

def summarize_text(text):
    try:
        # For 'text-generation' pipeline, the input might need to be structured for summarization
        # For BART, a common approach is to just pass the text and let the model generate
        result = summarizer(
            text,
            max_length=100,
            min_length=30,
            do_sample=False
        )
        return result[0]["generated_text"]
    except Exception as e:
        return f"Error: {str(e)}"

def answer_question(context, question):
    print("Q&A triggered.")
    try:
        return qa_pipeline(question=question, context=context)['answer']
    except Exception as e:
        return f"Error: {str(e)}"

def translate_text(text, language_code):
    print("Translation triggered.")
    try:
        return GoogleTranslator(source='auto', target=language_code).translate(text)
    except Exception as e:
        return f"Translation Error: {str(e)}"

def speak_text(text):
    print("TTS triggered.")
    try:
        tts = gTTS(text)
        tmp_path = tempfile.mktemp(".mp3")
        tts.save(tmp_path)
        return tmp_path
    except Exception as e:
        return f"Audio Error: {str(e)}"

def chat_with_gemini(prompt):
    try:
        response = client.models.generate_content(
    model="gemini-3-flash-preview", contents=prompt)
        return response.text
    except Exception as e:
        return f"Gemini Error: {str(e)}"

# --- Build Gradio Interface ---

with gr.Blocks() as edubot_ui:
    gr.Markdown("# 📘 EduBot - Smart Academic Companion")

    with gr.Tab("📸 OCR"):
        image_input = gr.Image(type="filepath", label="Upload Image")
        ocr_output = gr.Textbox(label="Extracted Text")
        gr.Button("Extract Text").click(ocr_from_image, inputs=image_input, outputs=ocr_output)

    with gr.Tab("📝 Summarization"):
        summary_input = gr.Textbox(lines=10, label="Enter Text")
        summary_output = gr.Textbox(label="Summary")
        gr.Button("Summarize").click(summarize_text, inputs=summary_input, outputs=summary_output)

    with gr.Tab("❓ Q&A"):
        context_input = gr.Textbox(lines=10, label="Context")
        question_input = gr.Textbox(label="Question")
        answer_output = gr.Textbox(label="Answer")
        gr.Button("Get Answer").click(answer_question, inputs=[context_input, question_input], outputs=answer_output)

    with gr.Tab("🌐 Translate"):
        translate_input = gr.Textbox(label="Text")
        language_code = gr.Dropdown(choices=["hi", "ta", "bn", "te", "gu"], label="Language Code")
        translate_output = gr.Textbox(label="Translated")
        gr.Button("Translate").click(translate_text, inputs=[translate_input, language_code], outputs=translate_output)

    with gr.Tab("🔊 Speak"):
        voice_text = gr.Textbox(label="Text to Speak")
        audio_output = gr.Audio(label="Audio")
        gr.Button("Speak").click(speak_text, inputs=voice_text, outputs=audio_output)

    with gr.Tab("🤖 Chat with Gemini"):
        chat_input = gr.Textbox(label="Prompt")
        chat_output = gr.Textbox(label="Gemini Response")
        gr.Button("Send").click(chat_with_gemini, inputs=chat_input, outputs=chat_output)

# --- Launch Gradio App ---
edubot_ui.launch(share=True)